services:
  - type: web
    name: MASTERBOT
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 main.py"
    envVars:
      - key: WEBHOOK
        value: false
      - key: CHAT_BASE_TOKEN
        value: false
      - key: API_ID
        value: false
      - key: API_HASH
        value: false
      - key: BOT_TOKEN
        value: false
      - key: PORT
        value: 8080
