services:
  - type: web
    name: flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 3 -k gevent -b 0.0.0.0:$PORT --timeout 60 --graceful-timeout 30 --access-logfile '-' --error-logfile '-' --preload --worker-connections 1000 main:app"
